### ISSUE TITLE
Suggested additions to .gitignore

### ISSUE THREAD

**Issue by cjchapman** [robofab-developers/fontPens#13]
(I was going to submit a pull-request for this, but I can't since I'm not a contributor, so I'll write it up here.)

Here are some suggestions for additions to `.gitignore`:
```
# directories created during build/install process
build/
dist/
Lib/fontPens.egg-info/

# PyCharm's directory
.idea/
```

**Comment by justvanrossum** [comment]
Done in https://github.com/robofab-developers/fontPens/commit/1540e4df8e5111fc9a48fe2172a3a6b8270c8f07, thanks!

**Comment by adrientetar** [comment]
> (I was going to submit a pull-request for this, but I can't since I'm not a contributor, so I'll write it up here.)

you can if you fork the repo, git is distributed.
