### ISSUE TITLE
Whereabouts of pens

### ISSUE THREAD

**Issue by arialcrime** [robofab-developers/fontPens#18]
Hello there,

I have been working on updating some code to Python 3 and I am currently stuck on:
`from robofab.pens.adapterPens import PointToSegmentPen`

Since I was unable to find this pen in fontPens and fonttools.pens I wanted to ask if this has been made obsolete by something else, renamed, restructured or if I just failed to search in the right places.

Thanks in advance for your help!

**Comment by anthrotype** [comment]
It should be in ufoLib.pointPen

**Comment by gferreira** [comment]
see also this [overview of RoboFab pens and their new locations](http://robofont.com/documentation/building-tools/toolkit/robofab-fontparts/#pens)

**Comment by arialcrime** [comment]
Awesome, thanks @gferreira for putting together that list.
