### ISSUE TITLE
What is ThresholdPointPen actually supposed to do?

### ISSUE THREAD

**Issue by jenskutilek** [robofab-developers/fontPens#19]
I just came across the fact that ThresholdPointPen only outputs straight segments. Curves are completely filtered from the output. Is this expected?

**Comment by benkiel** [comment]
That's how it's always worked in RoboFab, if I remember correctly.

**Comment by jenskutilek** [comment]
But ThresholdPen also filters curve segments for length, and not just discards them all, so maybe the PointPen version has been broken in RoboFab, too ;)
