### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jbicha** [robofab-developers/fontPens#31]
We are interested in removing the old ufolib from Debian and this is the last Debian package using it.

Please consider making a new fontPens release. Thanks!

**Comment by typemytype** [comment]
the ufoLib is already been replaced/removed as pointPens have moved completely into fontTools

see 
https://github.com/robofab-developers/fontPens/pull/28
https://github.com/robofab-developers/fontPens/pull/29

the 0.1.0 will contain old ufoLib imports, @benkiel could you tag? thanks

**Comment by benkiel** [comment]
Done and on pypi.
