### ISSUE TITLE
Travis-ci: build is failing on AMD64

### ISSUE THREAD

**Issue by sanjaymsh** [robofab-developers/fontPens#34]
Hi,

I am testing the travis-ci build and foung that its failing on AMD64 with below error:
"=================================== log end ====================================
ERROR: could not install deps [coverage>=4.3, pytest, fontparts>=0.8.1, FontTools[ufo,lxml,unicode]>=3.32.0]; v = InvocationError(u"/home/travis/build/sanjaymsh/fontPens/.tox/py27-cov/bin/pip install -v 'coverage>=4.3' pytest 'fontparts>=0.8.1' 'FontTools[ufo,lxml,unicode]>=3.32.0'", 1)
___________________________________ summary ____________________________________
ERROR:   py27-cov: could not install deps [coverage>=4.3, pytest, fontparts>=0.8.1, FontTools[ufo,lxml,unicode]>=3.32.0]; v = InvocationError(u"/home/travis/build/sanjaymsh/fontPens/.tox/py27-cov/bin/pip install -v 'coverage>=4.3' pytest 'fontparts>=0.8.1' 'FontTools[ufo,lxml,unicode]>=3.32.0'", 1)
The command "./.travis/run.sh" exited with 1.
cache.2
store build cache
Done. Your build exited with 1."

The full error log can be seen here: https://travis-ci.com/github/sanjaymsh/fontPens/builds/189737804

Please have a look on this.

Thanks !!

**Comment by justvanrossum** [comment]
I think this was fixed with #37
