### ISSUE TITLE
marginPen yields wrong results for transformed components

### ISSUE THREAD

**Issue by jenskutilek** [robofab-developers/fontPens#39]
`addComponent` fails to respect the component's transformation and measures the untransformed outlines.

https://github.com/robotools/fontPens/blob/5d087c905c3c18cf30acfd043f6835f331192dfc/Lib/fontPens/marginPen.py#L97-L103

I believe the `addComponent` method should just be deleted, so it is inherited from `BasePen` and handles components correctly.

**Comment by justvanrossum** [comment]
I agree.

**Comment by typemytype** [comment]
Could you make a PR? Thanks

**Comment by jenskutilek** [comment]
Thank you!

**Comment by Eigi** [comment]
Can you please make a new release? On PyPi is still the version which contains the bug described here.
Thanx
Eigi
