### ISSUE TITLE
could someone add a setup install script in pip style

### ISSUE THREAD

**Issue by typemytype** [robofab-developers/fontPens#4]
thanks!

@anthrotype maybe?

**Comment by anthrotype** [comment]
Github is acting weirdly today...

anyway, how about this 3df73f54efbc551d89f182994f24b41df2a43deb ?

**Comment by anthrotype** [comment]
I set the initial version to the customary `0.1.0.dev0`.
When we will cut the initial release of fontPens, we'll drop the `.dev0` and tag `0.1.0`.
Immediately after releasing, we will increment the third digit and append `.dev0` again, to open a new cycle of development for the following release.
It's all automated and requires no additional tools. It's implemented via two custom `setup.py` sub-commands:

1) `python setup.py bump_version --help`: increment the package version and commit the changes
```
Options for 'bump_version' command:
  --major  bump the first digit, for incompatible API changes
  --minor  bump the second digit, for new backward-compatible features
  --patch  bump the third digit, for bug fixes (default)
```

2) `python setup.py release --help`: tag a new release
```
Options for 'release' command:
  --message (-m)  message containing the release notes
```

**Comment by typemytype** [comment]
super thanks!
