### ISSUE TITLE
Upload package to PyPI

### ISSUE THREAD

**Issue by anthrotype** [robofab-developers/fontPens#7]
see https://github.com/adobe-type-tools/afdko/pull/230/files#r159970100

**Comment by miguelsousa** [comment]
@anthrotype pretty please 😉

**Comment by anthrotype** [comment]
I just uploaded fontPens 0.1.0 manually using twine, you should be now able to `pip install fontPens`
https://pypi.python.org/pypi/fontPens

Once we have Travis CI set up, we can configure it to upload wheels and sdist packages automatically upon tagged commits.

There are some fontPens tests that currently require fontParts so the latter will also need to be published on PyPI before we can run the fontPens tests on Travis.

~ ~ ~

Note that the release process should be relatively straightforward, with the custom setup.py sub-commands that I use lately in most of the font-related python projects, including this one. So anybody with commit access to a Github repo can do it. You will also need to sign up to PyPI and I need to add your username to the list of admins for each of the projects hosted on PyPI, but that's easy, just let me know and I'll add you. It's better to reduce the [:bus: factor](https://en.wikipedia.org/wiki/Bus_factor) :)

The release process goes like this:

1) when you are ready to make a new release, type this command:

```
python setup.py release
```

A text editor (i.e. the value of the `$EDITOR` environment variable, or if that's empty the `nano` editor) will open up and you can type some release notes that will be written as the git tag message (you don't need to also write a header with the version number, that's done automatically).  

2) Once you exit from the text editor, a new commit and a new tag with the correct version number will be added to the local repository. So you need to update the upstream repo with:

```
git push --follow-tags
```

3) If the Travis CI is configured, that will automatically trigger the packaging and uploading to PyPI. You only need to wait for it to be completed successfully. If Travis is not set up, you can create the distribution packages from your local machine and upload with the [`twine`](https://pypi.python.org/pypi/twine/1.9.1) command line tool.

```
python setup.py sdist bdist_wheel
twine upload -u anthrotype dist/*.whl dist/*.zip
```

You'll be prompted for the password.

4) After ensuring the distribution packages have been uploaded successfully to PyPI, you can complete the release process with this command:

```
python setup.py bump_version
```

This will bump the third, last digit of the version number, and also append a "developmental release tag" (conventionally `.dev0`). The purpose of this is to re-open the master branch for a new cycle of development.

If you're not familiar with PEP440, a /devN tag like in 0.1.1.dev0 means more recent that 0.1.0 but less recent than 0.1.1. In fact, the `release` sub-command above simply strips the `.dev0` from the version string, so that `0.1.1` becomes the new stable version. Once that's published, we increase it again and we guess that the next release will be a "patch" or "bugfix" kind of release (whereby the last digit increases).

Now, it may well be the case that new features gets introduced between two releases and one wishes to bump the minor (or second) digit instead, before releasing the new one.
That can be accomplished by using the same `bump_version` sub-command with an option:

```
python setup.py bump_version --minor
``` 

You can also do `--major` if some backward incompatible changes to the API have been introduced. Then you call `release` and proceed from point (1) above.


Adding the release notes to the git tag message has the advantage that they will also show up in the Github Releases page. Although you may have noticed that the text doesn't get formatted as markdown but shows up as code-like monospaced block.

https://github.com/robofab-developers/fontPens/releases/tag/v0.1.0

If you care about it (sometimes I do, as the release notes will then show up in the pyup.io bot automated PRs), you can manually click "Edit Tag" and copy-paste the content of the tag message in the github release text box (you also need to type the title of the release, which should be the same as the version number, e.g. v0.1.0).

**Comment by miguelsousa** [comment]
Thanks Cosimo.
