### ISSUE TITLE
Difference in getDigestPointsOnly behavior between robofab.pens.digestPen and fontPens.digestPointPen

### ISSUE THREAD

**Issue by cjchapman** [robofab-developers/fontPens#8]
I see a difference in behavior in the `getDigestPointsOnly()` method between `robofab.pens.digestPen` and `fontPens.digestPointPen`, and just wanted to check if this is expected:
```python
>>> from robofab.pens.digestPen import DigestPointPen
>>> pen = DigestPointPen()
>>> pen.beginPath()
>>> pen.addPoint((10, 10), "move", "True")
>>> pen.getDigestPointsOnly(needSort=False)
((10, 10),)


>>> from fontPens.digestPointPen import DigestPointPen
>>> pen = DigestPointPen()
>>> pen.beginPath()
>>> pen.addPoint((10, 10), "move", "True")
>>> pen.getDigestPointsOnly(needSort=False)
('beginPath', (10, 10))
```

This lead to the changes in lines 873 and 890 of CheckOutlinesUFO.py in this PR:
https://github.com/adobe-type-tools/afdko/pull/230/files

**Comment by cjchapman** [comment]
(If this is not expected behavior, I'd be happy to help by working on this issue.)

**Comment by typemytype** [comment]
this is an part of a bigger issue: we have `DigestPointPen`, `DataPointPen` and `RecordingPointPen` doing the same thing... I guess we have to agree on one implementation instead of 3 very similar things 

`DataPointPen` is, I guess, my mistake... and can be removed

cc @justvanrossum

**Comment by justvanrossum** [comment]
@typemytype:
I'm trying to look into whether `DigestPointPen` and `RecordingPointPen` could be folded together, but there are quite substantial differences. Although a `getDigest()` method could be added to `RecordingPointPen` that returns a hashable representation of the complete contour. Not sure how easy it would be to make that representation exactly the same is the current `DigestPointPen`. Or whether that is important at all. But this very issue seems to say that it may be.

`DataPointPen` is largely equivalent to `RecordingPointPen` except it splits contours from components, so it can't always exactly reproduce the calling sequence of a point pen. So I'm +1 on removing `DataPointPen`, oping that it's not yet used a lot in the wild.

**Comment by justvanrossum** [comment]
Btw. the change that @cjchapman mentions is caused by the addition of the `identifier` argument to `beginPath()`, which happened before `fontPens` existed. It seems rather accidental.

On the other hand, without `beginPath` being output, the "points only" digest is rather ambiguous, because all contour points are just concatenated together, contour info is lost completely.

I have no idea what the designed purpose of `getDigestPointsOnly()` was, the whole thing looks rather messy.
